### ISSUE TITLE
Shortcut? and a couple of feature requests

### ISSUE THREAD

**Issue by LaraSQP** [didier-v/GDBeautifier#1]
First of all, thank you very much for developing GDBeautifier.

Now, is there a way to add a shortcut to call GDBeautifier? I have not been able to find any.

Regarding additional features, could GDBeautifier check for parentheses and do as follows:

```
_process(delta) -> _process( delta )
get_node("someNode") -> get_node( "someNode" ) 
```

The alignment of assignments also adds to clarity. This would be another great feature.

```
var mode = false
var valid = false
var location = 4
var type = "qwerty"

var mode	= false
var valid	= false
var location	= 4
var type	= "qwerty"
```

Again, thank you for making this addon available to all.

Using 4.2.2., btw.

**Comment by wyattbiker** [comment]
Yes, adding a shortcut would be more convenient since you would not have to keep switching between plugin and your script screen. I think it would not be hard to implement to just execute the plugin.

**Comment by LaraSQP** [comment]
Much appreciated

**Comment by didier-v** [comment]
Hello,
The shortcut is a great idea, I'll see what I can do.
