### ISSUE TITLE
$node references

### ISSUE THREAD

**Issue by tobydjones** [didier-v/GDBeautifier#2]
I was looking for a plugin which would change "a=b" to "a = b", and this does the trick!

However, it adds spaces around '/' when it's in a $node reference, ie
```
$LoginScreen/LoginPanel.hide()
```
is changed to
```
$LoginScreen / LoginPanel.hide()
```
which I find a bit ugly, as it's not an operator, so I'd really like it if you could add an option to ignore $node references please.

**Comment by tobydjones** [comment]
I've created a version of this plugin that has an option of ignoring '/' in $node references

**Comment by wyattbiker** [comment]
Think you can make it work with %nodes as well?

**Comment by tobydjones** [comment]
I'll try... I got some feedback from the author about my edits including adding support for %
Node references aren't easy to identify, unfortunately, but I'll try...

**Comment by didier-v** [comment]
I fixed the issue with node references [in this commit](https://github.com/didier-v/GDBeautifier/commit/4cb43335d4b5a5594a6fc4d314f64988f862cc97).
