### ISSUE TITLE
Multi-line string literals should also not be processed.

### ISSUE THREAD

**Issue by wyattbiker** [didier-v/GDBeautifier#8]
Example of GDBeautify converting this mulitline string:
```gdscript
		var version_string="4"
		print("This plugin supports version %s or higher. 
				Please upgrade to 4/5 or 6" % [version_string])
```
to this:
```gdscript
		var version_string = "4"
		print("This plugin supports version % s or higher.
				Please upgrade to 4 / 5 or 6" % [version_string])
```
Notice how operator codes inside the multiline string are formatted with spaces. The Editor catches the % s with a message that it is unsupported format code.

I fix it manually.

**Comment by didier-v** [comment]
That's right, I didn't think about the multiline strings. I'll check that.

**Comment by didier-v** [comment]
@wyattbiker Can you please test this fix?
